# Generated by Django 4.2.5 on 2023-12-04 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 15, 54, 50, 689849, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
