# Generated by Django 4.2.5 on 2023-12-11 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_lesson_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 14, 19, 3, 413986, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
