# Generated by Django 4.2.5 on 2023-12-13 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_lesson_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 22, 40, 42, 577481, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
