# Generated by Django 4.2.7 on 2024-02-18 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_alter_lesson_date_created_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default='facults/default.png', upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 18, 16, 59, 777192, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
